name: Flatpak

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flatpak:
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-43
      options: --privileged

    strategy:
      matrix:
        arch:
        - x86_64
        #- aarch64
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        dnf -y install docker
      if: ${{ matrix.arch == 'aarch64' }}

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
      if: ${{ matrix.arch == 'aarch64' }}

    - uses: flatpak/flatpak-github-actions/flatpak-builder@v5
      with:
        bundle: clairvoyant.flatpak
        manifest-path: com.github.cassidyjames.clairvoyant.json
        cache-key: "flatpak-builder-${{ github.sha }}"
        arch: ${{ matrix.arch }}

